@startuml

title __BATAILLE-NAVALE's Class Diagram__\n


    class Main {
    }

    namespace Equipe {
      class equipe.EqBataillon {
      }
    }

    namespace Equipe {
      class equipe.EqPecheur {
      }
    }
  

    namespace Equipe {
      abstract class equipe.Equipe {
      }
    }

    namespace Exceptions {
      class exceptions.LimiteException {
      }
    }
  

    namespace Exceptions {
      class exceptions.OccupException {
      }
    }

    namespace Joueur {
      interface joueur.Humain {
      }
    }
  

    namespace Joueur {
      interface joueur.Ia {
      }
    }
  

    namespace Joueur {
      interface joueur.Joueur {
      }
    }
  

    namespace Manager {
      class manager.Commande {
      }
    }

    namespace Manager {
      class manager.Jeu {
      }
    }

    namespace Navire {
      class navire.Chalutier {
      }
    }
  

    namespace Navire {
      class navire.Destroyer {
      }
    }
  

    namespace Navire {
      abstract class navire.Navire {
      }
    }
  

    namespace Navire {
      abstract class navire.NavireProfondeur {
      }
    }
  
  namespace Navire {
      abstract class navire.NavireSurface {
      }
    }
  

    namespace Navire {
      class navire.SousMarin {
      }
    }
  

    namespace lateau {
      class plateau.CasePlateau {
      }
    }

    namespace Plateau {
      class plateau.Plateau {
      }
    }
  

    namespace Tools {
      enum Action {
      }
    }
  

    namespace Tools {
      enum Couleur {
      }
    }
  

    namespace Tools {
      enum Direction {
      }
    }
  

    namespace Tools {
      enum Nature {
      }
    }
  

    namespace Tools {
      enum Statut {
      }
    }
  

    namespace Tools {
      class tools.ToolCouleur {
      }
    }
  

    namespace Tools {
      enum TypeNav {
      }
    }
  

  equipe.EqBataillon -up-|> equipe.Equipe
  equipe.EqPecheur -up-|> equipe.Equipe
  equipe.Equipe .up.|> joueur.Humain
  equipe.Equipe .up.|> joueur.Ia
  equipe.Equipe o-- manager.Commande : myCommande
  equipe.Equipe o-- tools.Nature : myNature
  equipe.Equipe o-- tools.Statut : myStatut
  manager.Commande o-- tools.Action : actionChoisie
  manager.Commande o-- tools.Direction : directionChoisie
  manager.Commande o-- equipe.Equipe : equipe
  manager.Jeu o-- plateau.Plateau : plateau
  navire.Chalutier -up-|> navire.NavireSurface
  navire.Destroyer -up-|> navire.NavireSurface
  navire.Navire o-- tools.TypeNav : myType
  navire.NavireProfondeur -up-|> navire.Navire
  navire.NavireSurface -up-|> navire.Navire
  navire.SousMarin -up-|> navire.NavireProfondeur


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
